name: Docker build and push to Github Packages

on:
  push:
    branches:
      - master
      - staging

  pull_request:
    branches:
      - master
      - staging

env:
  IMAGE_NAME: openmappr

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check docker build
        run: docker build . --file Dockerfile --tag openmappr_build --build-arg script_file='run_docker_mode'

      - name: Log into Github Package registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push openmappr image to Github Packages
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag openmappr_build $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
